services:
  central-server:
    container_name: CentralServer
    image: niis/xroad-central-server:jammy-7.3.0
    restart: unless-stopped
    ports:
      - "80:80"
      - "4000:4000"
      - "4001:4001"
      - "4002:4002"
      - "8888:8888"
      - "8899:8899"
    networks:
      lab_network:
        ipv4_address: 10.10.0.50

  security-server-a:
    container_name: SecurityServer_A
    image: niis/xroad-security-server:jammy-7.3.0
    restart: unless-stopped
    ports:
      - "4100:4000"
      - "4101:8080"
    networks:
      lab_network:
        ipv4_address: 10.10.0.51

  security-server-b:
    container_name: SecurityServer_B
    image: niis/xroad-security-server:jammy-7.3.0
    restart: unless-stopped
    ports:
      - "4200:4000"
      - "4201:8080"
    networks:
      lab_network:
        ipv4_address: 10.10.0.52

networks:
  lab_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.0.0/24
